import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Red_Hat_Display, DM_Sans } from "next/font/google";
import Image from "next/image";
import Footer from "@/components/Footer";

const red_hat_display = Red_Hat_Display({
    subsets: ["latin"],
    variable: "--red-hat-display",
});

const dm_sans = DM_Sans({
    subsets: ["latin"],
    variable: "--dm-sans",
});

export const metadata: Metadata = {
    title: "All in for Sport",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${red_hat_display.variable} ${dm_sans.variable} bg-background overflow-x-hidden relative text-white font-body`}
            >
                <div className="max-w-screen">
                    <div className="max-w-xl lg:max-w-7xl mx-auto">
                        <Header />
                        {children}
                        <Footer />
                    </div>
                </div>
            </body>
        </html>
    );
}
