import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Red_Hat_Display, DM_Sans } from "next/font/google";
import Image from "next/image";

const red_hat_display = Red_Hat_Display({
    subsets: ["latin"],
    variable: "--red-hat-display",
});

const dm_sans = DM_Sans({
    subsets: ["latin"],
    variable: "--dm-sans",
});

export const metadata: Metadata = {
    title: "All in for Sport",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${red_hat_display.variable} ${dm_sans.variable} bg-background relative text-white font-body`}
            >
                <Image
                    className="absolute top-0 right-0 left-0 w-full min-w-screen flex-0 mx-auto"
                    src="/assets/noise.png"
                    width={1440}
                    height={1682}
                    alt=""
                />
                <div className="relative z-10 max-w-7xl mx-auto">
                    <Header />
                    {children}
                </div>
            </body>
        </html>
    );
}
